// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Mutation struct {
}

type NewTermInput struct {
	Term *string `json:"term,omitempty"`
	Def  *string `json:"def,omitempty"`
}

type Query struct {
}

type StudysetInput struct {
	Title   string `json:"title"`
	Private bool   `json:"private"`
}

type Term struct {
	ID        *string       `json:"id,omitempty"`
	Term      *string       `json:"term,omitempty"`
	Def       *string       `json:"def,omitempty"`
	Progress  *TermProgress `json:"progress,omitempty"`
	CreatedAt *string       `json:"created_at,omitempty"`
	UpdatedAt *string       `json:"updated_at,omitempty"`
}

type TermInput struct {
	ID   string  `json:"id"`
	Term *string `json:"term,omitempty"`
	Def  *string `json:"def,omitempty"`
}

type TermProgress struct {
	ID                   *string `json:"id,omitempty"`
	TermFirstReviewedAt  *string `json:"term_first_reviewed_at,omitempty"`
	TermLastReviewedAt   *string `json:"term_last_reviewed_at,omitempty"`
	TermReviewCount      *int32  `json:"term_review_count,omitempty"`
	DefFirstReviewedAt   *string `json:"def_first_reviewed_at,omitempty"`
	DefLastReviewedAt    *string `json:"def_last_reviewed_at,omitempty"`
	DefReviewCount       *int32  `json:"def_review_count,omitempty"`
	TermLeitnerSystemBox *int32  `json:"term_leitner_system_box,omitempty"`
	DefLeitnerSystemBox  *int32  `json:"def_leitner_system_box,omitempty"`
}

type TermProgressInput struct {
	TermFirstReviewedAt  *string `json:"term_first_reviewed_at,omitempty"`
	TermLastReviewedAt   *string `json:"term_last_reviewed_at,omitempty"`
	TermReviewCount      *int32  `json:"term_review_count,omitempty"`
	DefFirstReviewedAt   *string `json:"def_first_reviewed_at,omitempty"`
	DefLastReviewedAt    *string `json:"def_last_reviewed_at,omitempty"`
	DefReviewCount       *int32  `json:"def_review_count,omitempty"`
	TermLeitnerSystemBox *int32  `json:"term_leitner_system_box,omitempty"`
	DefLeitnerSystemBox  *int32  `json:"def_leitner_system_box,omitempty"`
}

type User struct {
	ID          *string `json:"id,omitempty"`
	Username    *string `json:"username,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
}

type AuthType string

const (
	AuthTypeUsernamePassword AuthType = "USERNAME_PASSWORD"
	AuthTypeOauthGoogle      AuthType = "OAUTH_GOOGLE"
)

var AllAuthType = []AuthType{
	AuthTypeUsernamePassword,
	AuthTypeOauthGoogle,
}

func (e AuthType) IsValid() bool {
	switch e {
	case AuthTypeUsernamePassword, AuthTypeOauthGoogle:
		return true
	}
	return false
}

func (e AuthType) String() string {
	return string(e)
}

func (e *AuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthType", str)
	}
	return nil
}

func (e AuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
